name: flutter_store_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  provider: ^6.0.5
  #  sqflite: ^2.2.6
  #  http: ^0.13.5
  #  intl: ^0.17.0
  google_fonts: ^4.0.3
#  modal_progress_hud_nsn: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: assets/fonts/Pacifico-Regular.ttf